### ISSUE TITLE
Full color support for LightStrips and Bloom Friends of hue

### ISSUE THREAD

**Issue by robwalch** [cees-elzinga/script.xbmc.hue.ambilight#23]
Don't correct color on lights that support full spectrum.

**Comment by tams89** [comment]
Tried it with bloom and Kodi Beta 1 it flashes on start of the video but then stays as it is, it does not update with the screen colours. It auto detects the bridge etc fine.

**Comment by robwalch** [comment]
@tams89 the latest Kodi Isengard beta for works for me on OSX. I have not tried using a Bloom. Maybe I'll pick one up.

What system are you running Kodi on? Make sure you configure the ambilight plugin - selecting the ambilight mode and lights you want it to use.

**Comment by tams89** [comment]
I'm on Windows 8.1. It is detected by the plugin automatically, and have selected the ambilight mode but no joy. I think its likely Bloom specific maybe there using different device Ids or some-such.
